FROM python:3.7-alpine
MAINTAINER James Alexander <j.alexanderbryant@gmail.com>

WORKDIR '/app'

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY ./ ./
RUN pip install --editable .

CMD gunicorn -b 0.0.0.0:8000 --access-logfile - "app.app:create_app()"
